### ISSUE TITLE
Copy error + how to use the local config YAML?

### ISSUE THREAD

**Issue by dandunckelman** [clns/gitlab-cli#1]
Cool project!

I can't seem to find any info on what I should put in the config YAML, and I'm not familiar enough with Go to try and figure out the required YAML structure.

I ask because I get an error when I try this (my **.gitlab-cli.yaml** is empty):

```
gitlab-cli label copy -u "https://git.my-site.com/my_group/my_project" -t "MY_TOKEN"
Using config file: /root/.gitlab-cli.yaml
error: invalid target repository: failed to get GitLab project 'https://git.my-site.com/my_group/my_project':
  Get https:/api/v3/projects/search/my_project:
    net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I see a few interesting things here:
1. The output seems to indicate that the API request is using an invalid URL
2. Doing a search for project by name will be problematic for me as I'm dealing w/ many groups having the same projects
- Hopefully, your code accounts for that and filters through the list of search results to get the project matching the group

Please let me know what I'm doing wrong here and what the config file should contain.

Thanks

**Comment by clns** [comment]
I'm glad you find it useful. I updated the README with information about [the config file](https://github.com/clns/gitlab-cli#the-config-file) and how to [specify a repository](https://github.com/clns/gitlab-cli#specifying-a-repository).

Based on your usage, you don't need the config file. The problem is most likely that the URL you provided is invalid, since the request times out. Can you double check the URL?

> 1 The output seems to indicate that the API request is using an invalid URL

I guess you're referring to `Get https:/api/v3/projects/search/my_project:` - this is not actually a problem with the URL, it's bad output from [xanzy/go-gitlab](https://github.com/xanzy/go-gitlab).

> 2 Doing a search for project by name will be problematic for me as I'm dealing w/ many groups having the same projects

This is not a problem, because it actually searches for the project by its path, so you'll be good. The reason you see this is because GitLab API only allows searching by name, but then my code filters it out and only returns the repo that matches the given path.

I've release [0.2.0](https://github.com/clns/gitlab-cli/releases) and I recommend you update to it. In this release there's a new `update` command which will make [updating much easier](https://github.com/clns/gitlab-cli#update), but for now you'll have to re-run the command from the [releases page](https://github.com/clns/gitlab-cli/releases).

Also after updating make sure you use `-U` (uppercase) instead of `-u` when specifying the URL since `-u` is now used for the user.

I'll keep this issue open and feel free to comment back with any other questions.

**Comment by dandunckelman** [comment]
Thanks for updating the README!

You were right about my not needing the config.  Ultimately, I had a networking issue on my internal LAN.  I switched to a different machine that could properly talk to the Gitlab server, updated to v0.2.0 and voila!

Thanks for the help!
