### ISSUE TITLE
Documentation for copying is unclear

### ISSUE THREAD

**Issue by MDCore** [clns/gitlab-cli#5]
I want to copy the labels from Repository A to Repository B. I can't work out from the docs how to do that, and the various I'm trying don't seem to work. how might I do that given that I've configured `repoA` and `repoB` in the yaml file?

**Comment by clns** [comment]
If you have the repositories configured in the [config file](https://github.com/clns/gitlab-cli#the-config-file), you can refer to them by name, e.g.:

```
gitlab label copy -r repoB repoA
```

The above command will copy the labels from "repoA" into "repoB".

If you have suggestions on how this command can be changed in order to make it easier to understand, I'd be happy to hear them.

**Comment by clns** [comment]
I updated my previous comment to use repoA and repoB, and reversed the order since it wasn't correct.

**Comment by MDCore** [comment]
aaah, that's probably why it didn't work for me, I had it backwards

**Comment by MDCore** [comment]
I guess my feedback would be that it's not clear what the source repo and target repo is in the docs. Some of the examples don't appear to specify a target and I was a bit confused by that too.

Happy to close this ticket :)

**Comment by clns** [comment]
FIY, I updated the README with more clear usage. Thanks for reporting this.

**Comment by MDCore** [comment]
That's perfect. Thank you, and thanks for the tool!
